# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CppEigenInv <- function(X) {
    .Call('_dogss_CppEigenInv', PACKAGE = 'dogss', X)
}

CppEigenWoodbury <- function(V2, X, Sigma2_0) {
    .Call('_dogss_CppEigenWoodbury', PACKAGE = 'dogss', V2, X, Sigma2_0)
}

CppEigenVtimesNu <- function(V, nu) {
    .Call('_dogss_CppEigenVtimesNu', PACKAGE = 'dogss', V, nu)
}

